site_name: Belajar JavaScript Pemula
nav:
  - Home: index.md
  - Dasar:
      - "01. Hello World": dasar/01-hello-world.md
      - "02. Variabel": dasar/02-Variabel.md
      # lanjutkan dengan file lainmu
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
